[package]
name = "dem-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
glfw = "0.58.0"
nalgebra-glm = "0.3"
image = "0.25.6"
opencv = "0.94.4"
user32-sys = "0.2.0"
geotiff = "*"
tiff = "*"
serde = "1.0.219"
serde_json = "1.0"
