[package]
name = "dem-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
glfw = "0.58.0"
nalgebra-glm = "0.3"
gdal-win = "*"
image = "0.25.6"

[build-dependencies]
gdal-setup = "*"